:bacuse_frameworks!
use_frameworks!

target 'STWUITestingKit_Example' do
    pod 'STWUITestingKit', :path => '../'

  target 'STWUITestingKit_Tests' do
    inherit! :search_paths


  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            if "#{config}" == "Debug"
                config.build_settings['ENABLE_TESTABILITY'] = 'YES'
            end
        end
    end
end
