use_frameworks!

target 'STWUITestingKit_Example' do
  
  pod 'Reveal-iOS-SDK', '~> 1.6', :configurations => ['Debug']
  
  target 'STWUITestingKit_Tests' do
      inherit! :search_paths
      pod 'STWUITestingKit', :path => '../'
  end
  
  target 'STWUITestingKit_UITests' do
    inherit! :search_paths
    pod 'STWUITestingKit', :path => '../'
  end
end
