use_frameworks!

target 'STWUITestingKit_Example' do
  
  target 'STWUITestingKit_Tests' do
      inherit! :search_paths
      pod 'STWUITestingKit', :path => '../'
  end
  
  target 'STWUITestingKit_UITests' do
    inherit! :search_paths
    pod 'STWUITestingKit', :path => '../'
  end
end
